[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
lib_deps =
    https://github.com/earlephilhower/BackgroundAudio/archive/refs/tags/1.4.4.zip
    h2zero/NimBLE-Arduino@^2.5.0
    bblanchon/ArduinoJson
build_flags = -O3
extra_scripts = pre:patchlib.py
board_build.embed_txtfiles =
    res/config.html